development:
  adapter: postgresql
  encoding: utf8
  database: object_state
  username:
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: object_state_test
  username:
  password:
  host: localhost
