# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10df7a2d360aa304cbf13b9d860c73e3feca176642a5b20bdcaf4207865cff375ba01067f945dc95e3c93afa136e16e964ae21c61f58e424f734098e09788537

test:
  secret_key_base: fe58dd97bd90793033e865bda340f6bb699226241903268a8865b020e2228f3c2af93318b082faf1475297b808c3a5c8ca29c1b95a45c69b6f47772b4320ec67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
